spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8809
spring:
  profiles: dev
  application:
    name: springcloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/   
---
server: 
  port: 8819 
spring:
  profiles: test
  application:
    name: springcloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
